[build]
      publish = "public"
      command = "hugo"
    # build a preview of the site [hugo --buildFuture]
    [context.deploy-preview]
      command = "hugo --buildFuture"
    # The default version you use for production if you don't use context
    [build.environment]
<<<<<<< HEAD
      HUGO_VERSION = "0.73.0"
    # The version you use for production
    [context.production.environment]
      HUGO_VERSION = "0.73.0"
    # you can lock a version of hugo for a deploy preview
    [context.deploy-preview.environment]
      HUGO_VERSION = "0.73.0"
    # you can lock a version of hugo for a branch-deploy (other than previews)
    [context.branch-deploy.environment]
      HUGO_VERSION = "0.73.0"
=======
      HUGO_VERSION = "0.62.2"
    # The version you use for production
    [context.production.environment]
      HUGO_VERSION = "0.62.2"
    # you can lock a version of hugo for a deploy preview
    [context.deploy-preview.environment]
      HUGO_VERSION = "0.62.2"
    # you can lock a version of hugo for a branch-deploy (other than previews)
    [context.branch-deploy.environment]
      HUGO_VERSION = "0.62.2"
>>>>>>> 2307ea464db31e47951503eb76688230f4292ed6
